#!/usr/bin/env bash
#SBATCH --job-name=prepare-phase2-q2
#SBATCH --nodes=1
#SBATCH --partition=boost_usr_prod
#SBATCH --account=oellm_prod2026
#SBATCH --qos=boost_qos_lprod
#SBATCH --gpus=a100:1
#SBATCH --time=24:00:00
#SBATCH --output=logs/%j.%x.out
#SBATCH --error=logs/%j.%x.err
#SBATCH --mem=128G

# Phase 2 Experiment Q2: Tokenize curated Dolci FC + TxT360-random (365,200 samples).
#
# AMS control: randomly removes the same number of TxT360 samples as A3's
# AMS-targeted filtering (162,165 from 187,191). Compare A3 vs Q2 to isolate
# the AMS filtering effect from volume reduction.
#
# K-replication: set SEED to a non-empty value to tokenize a paired replication.
# SEED selects the input file txt360_random_seed${SEED}.jsonl (regenerated by
# fcanalysis/scripts/regen_txt360_random.py with the matching --seeds value)
# and suffixes OUTPUT_DIR with _seed${SEED}. Run once per replication seed.
#
# Prerequisites:
#   - Dolci-format JSONLs at $PHASE2_DIR/{dolci,txt360_random[_seed${SEED}]}.jsonl
#     Generated by convert_openai_to_dolci_format.py from fcanalysis phase2_data.
#
# Usage:
#   mkdir -p logs
#   sbatch prepare_phase2_q2_data.sh                     # default (txt360_random.jsonl)
#   SEED=42 sbatch prepare_phase2_q2_data.sh              # replication k=42
#   SEED=7  sbatch prepare_phase2_q2_data.sh              # replication k=7
#   SEED=13 sbatch prepare_phase2_q2_data.sh              # replication k=13

set -euo pipefail

WORK_DIR="${WORK}/ytahtah0"
mkdir -p "$WORK_DIR"

export HF_HOME="${WORK_DIR}/.cache/huggingface"
export HF_DATASETS_CACHE="${WORK_DIR}/.cache/huggingface/datasets"
export HF_HUB_OFFLINE=1
export TRANSFORMERS_OFFLINE=1
export HF_DATASETS_OFFLINE=1

source /leonardo/home/userexternal/ytahtah0/open-instruct/.venv/bin/activate

# K-replication: SEED unset → uses txt360_random.jsonl (default seed=42 from
# fcanalysis prepare_phase2_data.py). SEED=N → uses txt360_random_seed${N}.jsonl.
SEED="${SEED:-}"
SEED_SUFFIX="${SEED:+_seed${SEED}}"
TXT360_RANDOM_BASENAME="txt360_random${SEED_SUFFIX}.jsonl"

PROJECT_ROOT="${PROJECT_ROOT:-/leonardo/home/userexternal/ytahtah0/open-instruct}"
PHASE2_DIR="${PHASE2_DIR:-${WORK_DIR}/data/phase2}"
DOLCI_JSONL="${PHASE2_DIR}/dolci.jsonl"
TXT360_RANDOM_JSONL="${PHASE2_DIR}/${TXT360_RANDOM_BASENAME}"
OUTPUT_DIR="${OUTPUT_DIR:-${WORK_DIR}/data/phase2_q2_tokenized${SEED_SUFFIX}}"
TOKENIZER="${TOKENIZER:-allenai/Olmo-3-7B-Instruct-SFT}"
DATASET_CACHE_DIR="${WORK_DIR}/local_dataset_cache"

echo "=== Phase 2 Q2: Curated Dolci + TxT360-random FC Data Preparation ==="
echo "Job ID: ${SLURM_JOB_ID:-local}"
echo "Replication SEED: ${SEED:-(default)}"
echo "Dolci JSONL: $DOLCI_JSONL"
echo "TxT360-random JSONL: $TXT360_RANDOM_JSONL"
echo "Output: $OUTPUT_DIR"
echo "======================================================================"

for f in "$DOLCI_JSONL" "$TXT360_RANDOM_JSONL"; do
    if [ ! -f "$f" ]; then
        echo "ERROR: $f not found."
        exit 1
    fi
done

mkdir -p "$OUTPUT_DIR"
cd "$PROJECT_ROOT"

python scripts/data/convert_sft_data_for_olmocore.py \
    --tokenizer_name_or_path "$TOKENIZER" \
    --dataset_mixer_list "$DOLCI_JSONL" 1.0 "$TXT360_RANDOM_JSONL" 1.0 \
    --output_dir "$OUTPUT_DIR" \
    --dataset_local_cache_dir "$DATASET_CACHE_DIR" \
    --max_seq_length 32768 \
    --visualize True \
    --resume \
    --checkpoint_interval 50000

echo "=== Data preparation complete ==="
echo "Output saved to: $OUTPUT_DIR"
