#!/usr/bin/env bash
#SBATCH --job-name=prepare-phase2-q1
#SBATCH --nodes=1
#SBATCH --partition=boost_usr_prod
#SBATCH --account=oellm_prod2026
#SBATCH --qos=boost_qos_lprod
#SBATCH --gpus=a100:1
#SBATCH --time=24:00:00
#SBATCH --output=logs/%j.%x.out
#SBATCH --error=logs/%j.%x.err
#SBATCH --mem=128G

# Phase 2 Experiment Q1: Tokenize curated Dolci FC + TxT360-full (390,226 samples).
#
# Q1 is the TxT360 analog of A2 (the "no removal" anchor in the v1 trio).
# Together with A3 (AMS-filtered) and Q2 (random control), the TxT360 trio
# mirrors the v1 trio (A2 / A2' / Q4):
#
#   Q1 = Dolci + TxT360-full       (187,191)   total 390,226   no AMS removal
#   A3 = Dolci + TxT360-ams        (162,165)   total 365,200   AMS-targeted removal
#   Q2 = Dolci + TxT360-random     (162,165)   total 365,200   random removal
#
# Comparisons the trio enables:
#   - Q1 vs A3: "no AMS filter vs AMS-filtered" — volume-confounded ~7%
#   - A3 vs Q2: "AMS-targeted vs random removal" — volume + step matched (headline)
#   - Q1 vs Q2: "full vs random subsample" — pure volume
#
# txt360_full.jsonl is the post-dedup pre-AMS snapshot: 187,191 samples after
# universal filters + within-dataset dedup + cross-dataset dedup vs v1
# (260,527 → 242,655 → 187,191). The only thing NOT applied is the AMS filter.
#
# Prerequisites:
#   - Dolci-format JSONLs at $PHASE2_DIR/{dolci,txt360_full}.jsonl
#     Generated by convert_openai_to_dolci_format.py from fcanalysis phase2_data.
#
# Usage:
#   mkdir -p logs
#   sbatch prepare_phase2_q1_data.sh

set -euo pipefail

WORK_DIR="${WORK}/ytahtah0"
mkdir -p "$WORK_DIR"

export HF_HOME="${WORK_DIR}/.cache/huggingface"
export HF_DATASETS_CACHE="${WORK_DIR}/.cache/huggingface/datasets"
export HF_HUB_OFFLINE=1
export TRANSFORMERS_OFFLINE=1
export HF_DATASETS_OFFLINE=1

source /leonardo/home/userexternal/ytahtah0/open-instruct/.venv/bin/activate

PROJECT_ROOT="${PROJECT_ROOT:-/leonardo/home/userexternal/ytahtah0/open-instruct}"
PHASE2_DIR="${PHASE2_DIR:-${WORK_DIR}/data/phase2}"
DOLCI_JSONL="${PHASE2_DIR}/dolci.jsonl"
TXT360_FULL_JSONL="${PHASE2_DIR}/txt360_full.jsonl"
OUTPUT_DIR="${OUTPUT_DIR:-${WORK_DIR}/data/phase2_q1_tokenized}"
TOKENIZER="${TOKENIZER:-allenai/Olmo-3-7B-Instruct-SFT}"
DATASET_CACHE_DIR="${WORK_DIR}/local_dataset_cache"

echo "=== Phase 2 Q1: Curated Dolci + TxT360-full FC Data Preparation ==="
echo "Job ID: ${SLURM_JOB_ID:-local}"
echo "Dolci JSONL: $DOLCI_JSONL"
echo "TxT360-full JSONL: $TXT360_FULL_JSONL"
echo "Output: $OUTPUT_DIR"
echo "==================================================================="

for f in "$DOLCI_JSONL" "$TXT360_FULL_JSONL"; do
    if [ ! -f "$f" ]; then
        echo "ERROR: $f not found."
        exit 1
    fi
done

mkdir -p "$OUTPUT_DIR"
cd "$PROJECT_ROOT"

python scripts/data/convert_sft_data_for_olmocore.py \
    --tokenizer_name_or_path "$TOKENIZER" \
    --dataset_mixer_list "$DOLCI_JSONL" 1.0 "$TXT360_FULL_JSONL" 1.0 \
    --output_dir "$OUTPUT_DIR" \
    --dataset_local_cache_dir "$DATASET_CACHE_DIR" \
    --max_seq_length 32768 \
    --visualize True \
    --resume \
    --checkpoint_interval 50000

echo "=== Data preparation complete ==="
echo "Output saved to: $OUTPUT_DIR"
