#!/usr/bin/env bash
#SBATCH --job-name=prepare-phase2-p1
#SBATCH --nodes=1
#SBATCH --partition=boost_usr_prod
#SBATCH --account=oellm_prod2026
#SBATCH --qos=boost_qos_lprod
#SBATCH --gpus=a100:1
#SBATCH --time=24:00:00
#SBATCH --output=logs/%j.%x.out
#SBATCH --error=logs/%j.%x.err
#SBATCH --mem=128G

# Phase 2 Experiment P1: Tokenize curated Dolci FC only (203,035 samples).
#
# Anchor for all add-one comparisons. Uses the curated pipeline output
# from fcanalysis, converted to Dolci format.
#
# Prerequisites:
#   - Dolci-format JSONL at $PHASE2_DIR/dolci.jsonl
#     Generated by: python scripts/data/convert_openai_to_dolci_format.py \
#                       --input /path/to/fcanalysis/phase2_data/dolci.jsonl \
#                       --output $PHASE2_DIR/dolci.jsonl
#
# Usage:
#   mkdir -p logs
#   sbatch prepare_phase2_p1_data.sh

set -euo pipefail

WORK_DIR="${WORK}/ytahtah0"
mkdir -p "$WORK_DIR"

export HF_HOME="${WORK_DIR}/.cache/huggingface"
export HF_DATASETS_CACHE="${WORK_DIR}/.cache/huggingface/datasets"
export HF_HUB_OFFLINE=1
export TRANSFORMERS_OFFLINE=1
export HF_DATASETS_OFFLINE=1

source /leonardo/home/userexternal/ytahtah0/open-instruct/.venv/bin/activate

PROJECT_ROOT="${PROJECT_ROOT:-/leonardo/home/userexternal/ytahtah0/open-instruct}"
PHASE2_DIR="${PHASE2_DIR:-${WORK_DIR}/data/phase2}"
DOLCI_JSONL="${PHASE2_DIR}/dolci.jsonl"
OUTPUT_DIR="${OUTPUT_DIR:-${WORK_DIR}/data/phase2_p1_tokenized}"
TOKENIZER="${TOKENIZER:-allenai/Olmo-3-7B-Instruct-SFT}"
DATASET_CACHE_DIR="${WORK_DIR}/local_dataset_cache"

echo "=== Phase 2 P1: Curated Dolci FC Data Preparation ==="
echo "Job ID: ${SLURM_JOB_ID:-local}"
echo "Dolci JSONL: $DOLCI_JSONL"
echo "Output: $OUTPUT_DIR"
echo "======================================================"

if [ ! -f "$DOLCI_JSONL" ]; then
    echo "ERROR: $DOLCI_JSONL not found."
    echo "Run: python scripts/data/convert_openai_to_dolci_format.py --input <fcanalysis>/phase2_data/dolci.jsonl --output $DOLCI_JSONL"
    exit 1
fi

mkdir -p "$OUTPUT_DIR"
cd "$PROJECT_ROOT"

python scripts/data/convert_sft_data_for_olmocore.py \
    --tokenizer_name_or_path "$TOKENIZER" \
    --dataset_mixer_list "$DOLCI_JSONL" 1.0 \
    --output_dir "$OUTPUT_DIR" \
    --dataset_local_cache_dir "$DATASET_CACHE_DIR" \
    --max_seq_length 32768 \
    --visualize True \
    --resume \
    --checkpoint_interval 50000

echo "=== Data preparation complete ==="
echo "Output saved to: $OUTPUT_DIR"
