#!/usr/bin/env bash
#SBATCH --job-name=prepare-phase2-p2
#SBATCH --nodes=1
#SBATCH --partition=boost_usr_prod
#SBATCH --account=oellm_prod2026
#SBATCH --qos=boost_qos_lprod
#SBATCH --gpus=a100:1
#SBATCH --time=24:00:00
#SBATCH --output=logs/%j.%x.out
#SBATCH --error=logs/%j.%x.err
#SBATCH --mem=150G

# Phase 2 Experiment P2: Tokenize full IT+FC mix (~2,513,470 samples).
#
# IT-only(~1,924,533) + Dolci-FC(203,035) + GS(23,427) + v1-dedup(200,310) + TxT360-AMS(162,165).
# Pre-specified best-recipe ceiling. IT+FC recipe (8 nodes, LR 8e-5, ~1M batch, 2 epochs).
#
# NOTE: 150G mem required — Phase 1 K (similar scale) OOMed at 128G during tokenization.
#
# Prerequisites:
#   - dolci_it_only.parquet at $DOLCI_IT_ONLY (from Phase 1 filter_dolci_it_only.py)
#   - Dolci-format JSONLs at $PHASE2_DIR/{dolci,graphsyn,v1_dedup,txt360_ams}.jsonl
#     Generated by convert_openai_to_dolci_format.py from fcanalysis phase2_data.
#
# Usage:
#   mkdir -p logs
#   sbatch prepare_phase2_p2_data.sh

set -euo pipefail

WORK_DIR="${WORK}/ytahtah0"
mkdir -p "$WORK_DIR"

export HF_HOME="${WORK_DIR}/.cache/huggingface"
export HF_DATASETS_CACHE="${WORK_DIR}/.cache/huggingface/datasets"
export HF_HUB_OFFLINE=1
export TRANSFORMERS_OFFLINE=1
export HF_DATASETS_OFFLINE=1

source /leonardo/home/userexternal/ytahtah0/open-instruct/.venv/bin/activate

PROJECT_ROOT="${PROJECT_ROOT:-/leonardo/home/userexternal/ytahtah0/open-instruct}"
DOLCI_IT_ONLY="${DOLCI_IT_ONLY:-${WORK_DIR}/data/dolci_it_only.parquet}"
PHASE2_DIR="${PHASE2_DIR:-${WORK_DIR}/data/phase2}"
DOLCI_JSONL="${PHASE2_DIR}/dolci.jsonl"
GRAPHSYN_JSONL="${PHASE2_DIR}/graphsyn.jsonl"
V1_DEDUP_JSONL="${PHASE2_DIR}/v1_dedup.jsonl"
TXT360_AMS_JSONL="${PHASE2_DIR}/txt360_ams.jsonl"
OUTPUT_DIR="${OUTPUT_DIR:-${WORK_DIR}/data/phase2_p2_tokenized}"
TOKENIZER="${TOKENIZER:-allenai/Olmo-3-7B-Instruct-SFT}"
DATASET_CACHE_DIR="${WORK_DIR}/local_dataset_cache"

echo "=== Phase 2 P2: Full IT+FC Mix Data Preparation ==="
echo "Job ID: ${SLURM_JOB_ID:-local}"
echo "Dolci IT-only: $DOLCI_IT_ONLY"
echo "Dolci FC JSONL: $DOLCI_JSONL"
echo "GraphSyn JSONL: $GRAPHSYN_JSONL"
echo "v1-dedup JSONL: $V1_DEDUP_JSONL"
echo "TxT360-AMS JSONL: $TXT360_AMS_JSONL"
echo "Output: $OUTPUT_DIR"
echo "======================================================"

for f in "$DOLCI_IT_ONLY" "$DOLCI_JSONL" "$GRAPHSYN_JSONL" "$V1_DEDUP_JSONL" "$TXT360_AMS_JSONL"; do
    if [ ! -f "$f" ]; then
        echo "ERROR: $f not found."
        exit 1
    fi
done

mkdir -p "$OUTPUT_DIR"
cd "$PROJECT_ROOT"

python scripts/data/convert_sft_data_for_olmocore.py \
    --tokenizer_name_or_path "$TOKENIZER" \
    --dataset_mixer_list "$DOLCI_IT_ONLY" 1.0 "$DOLCI_JSONL" 1.0 "$GRAPHSYN_JSONL" 1.0 "$V1_DEDUP_JSONL" 1.0 "$TXT360_AMS_JSONL" 1.0 \
    --output_dir "$OUTPUT_DIR" \
    --dataset_local_cache_dir "$DATASET_CACHE_DIR" \
    --max_seq_length 32768 \
    --visualize True \
    --resume \
    --checkpoint_interval 50000

echo "=== Data preparation complete ==="
echo "Output saved to: $OUTPUT_DIR"
