#!/usr/bin/env bash
#SBATCH --job-name=prepare-phase2-a2
#SBATCH --nodes=1
#SBATCH --partition=boost_usr_prod
#SBATCH --account=oellm_prod2026
#SBATCH --qos=boost_qos_lprod
#SBATCH --gpus=a100:1
#SBATCH --time=24:00:00
#SBATCH --output=logs/%j.%x.out
#SBATCH --error=logs/%j.%x.err
#SBATCH --mem=128G

# Phase 2 Experiment A2: Tokenize curated Dolci FC + v1-dedup (403,345 samples).
#
# Tests Nemotron v1 contribution to Multi-Turn. Compare A2 vs P1.
#
# Prerequisites:
#   - Dolci-format JSONLs at $PHASE2_DIR/{dolci,v1_dedup}.jsonl
#     Generated by convert_openai_to_dolci_format.py from fcanalysis phase2_data.
#
# Usage:
#   mkdir -p logs
#   sbatch prepare_phase2_a2_data.sh

set -euo pipefail

WORK_DIR="${WORK}/ytahtah0"
mkdir -p "$WORK_DIR"

export HF_HOME="${WORK_DIR}/.cache/huggingface"
export HF_DATASETS_CACHE="${WORK_DIR}/.cache/huggingface/datasets"
export HF_HUB_OFFLINE=1
export TRANSFORMERS_OFFLINE=1
export HF_DATASETS_OFFLINE=1

source /leonardo/home/userexternal/ytahtah0/open-instruct/.venv/bin/activate

PROJECT_ROOT="${PROJECT_ROOT:-/leonardo/home/userexternal/ytahtah0/open-instruct}"
PHASE2_DIR="${PHASE2_DIR:-${WORK_DIR}/data/phase2}"
DOLCI_JSONL="${PHASE2_DIR}/dolci.jsonl"
V1_DEDUP_JSONL="${PHASE2_DIR}/v1_dedup.jsonl"
OUTPUT_DIR="${OUTPUT_DIR:-${WORK_DIR}/data/phase2_a2_tokenized}"
TOKENIZER="${TOKENIZER:-allenai/Olmo-3-7B-Instruct-SFT}"
DATASET_CACHE_DIR="${WORK_DIR}/local_dataset_cache"

echo "=== Phase 2 A2: Curated Dolci + v1-dedup FC Data Preparation ==="
echo "Job ID: ${SLURM_JOB_ID:-local}"
echo "Dolci JSONL: $DOLCI_JSONL"
echo "v1-dedup JSONL: $V1_DEDUP_JSONL"
echo "Output: $OUTPUT_DIR"
echo "================================================================="

for f in "$DOLCI_JSONL" "$V1_DEDUP_JSONL"; do
    if [ ! -f "$f" ]; then
        echo "ERROR: $f not found."
        exit 1
    fi
done

mkdir -p "$OUTPUT_DIR"
cd "$PROJECT_ROOT"

python scripts/data/convert_sft_data_for_olmocore.py \
    --tokenizer_name_or_path "$TOKENIZER" \
    --dataset_mixer_list "$DOLCI_JSONL" 1.0 "$V1_DEDUP_JSONL" 1.0 \
    --output_dir "$OUTPUT_DIR" \
    --dataset_local_cache_dir "$DATASET_CACHE_DIR" \
    --max_seq_length 32768 \
    --visualize True \
    --resume \
    --checkpoint_interval 50000

echo "=== Data preparation complete ==="
echo "Output saved to: $OUTPUT_DIR"
